Sprint 2
pbologan/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-14 20:32 UTC by pbologan

2022-08-15 10:16 UTC, podlovchenko requested changes
Привет) Не увидела работу с другими страницами, помимо страницы авторизации
Также было бы здорово настроить работу eslint

2022-08-15 10:16 UTC, podlovchenko commented on src/utils/http-transport.ts
> +            // eslint-disable-next-line no-plusplus
Eslint стоит настроить так, чтобы не приходилось выключать правила
Либо следовать правилам

2022-08-15 10:16 UTC, podlovchenko commented on src/utils/http-transport.ts
> +enum METHOD {
enum обычно именуется в формате PascalCase

2022-08-15 10:16 UTC, podlovchenko commented on src/utils/http-transport.ts
> +  method: METHOD,
Могут быть необязательными

2022-08-15 10:16 UTC, podlovchenko commented on src/utils/http-transport.ts
> +}
Зачем жесткая привязка data к такому формату?

2022-08-15 10:16 UTC, podlovchenko commented on src/utils/http-transport.ts
> +  request(url: string, options: Options, timeout = 5000) {
Было бы здорово определить тип возвращаемого значения дженериком, так можно было бы указывать тип извне

2022-08-15 10:16 UTC, podlovchenko commented on src/core/Block.ts
> +export default class Block<P = any> {
Скорее
```suggestion
export default class Block<P extends object> {
```

2022-08-15 10:16 UTC, podlovchenko commented on src/components/error/error.ts
> +export default class Error extends Block {
```suggestion
export default class Error extends Block<ErrorProps> {
```

2022-08-15 10:16 UTC, podlovchenko commented on src/components/error/error.ts
> +}
Нигде не используется

2022-08-15 10:16 UTC, podlovchenko commented on src/components/error/error.css
> +}
В проекте в некоторых файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-15 11:15 UTC, pbologan commented
> Привет) Не увидела работу с другими страницами, помимо страницы авторизации Также было бы здорово настроить работу eslint

Привет! Спасибо большое за ревью и ценные замечания) Я ещё в процессе работы над остальными страницами, не успел доделать до конца дедлайна. Много потерял времени с тем, чтобы разобраться как использовать pug с его отступами для разметки в компонентах, в конце концов решил переехать на handlebars и работа пошла быстрее)

2022-08-15 11:24 UTC, pbologan commented on tsconfig.json
> +    // "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
Можешь, пожалуйста, пояснить этот момент? Раскомментировать всё в конфигурационном файле не лучшая идея, я так понимаю?) Но при этом хочется оставить закомментированные строчки на тот случай, если придётся варьировать настройками, так как у меня пока нет полного понимания, что мне понадобится в проекте, а что нет.
Кстати, ещё у меня не проходит автоматический тест на GitHub из-за tsconfig.json. Не могу понять конкретно из-за чего.

2022-08-17 15:44 UTC, podlovchenko approved these changes
Привет)

Сейчас при обновлении страницы `Cannot GET /signup`, нужно поправить в server.js
```
app.get('/*', (req, res) => {
  res.sendFile(resolve(__dirname, 'dist', 'index.html'));
});
```

Работу принимаю)

2022-08-17 15:44 UTC, podlovchenko commented on src/components/controlled-input/controlled-input.ts
> +        }
Можно короче записать
```suggestion
  error?.setProps({ text: validationResult });
```

2022-08-17 15:44 UTC, podlovchenko commented on src/pages/chat/chats-list/chats-list.ts
> +  constructor({ ...props }) {
```suggestion
  constructor(props) {
```

2022-08-17 15:44 UTC, podlovchenko commented on src/pages/chat/messages-list/header/index.ts
> +export default MessagesHeader;
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-08-17 21:46 UTC, pbologan commented on src/pages/chat/messages-list/header/index.ts
> +export default MessagesHeader;
Спасибо большое, это важный момент!

2022-08-17 21:46 UTC, merged